--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Swift-Strider/Sounds
build-by-default: true
branches:
- main
projects:
  Sounds:
    path: ""
    model: virion
    type: library
...
